"""Tests for ``core.cadence_netlist`` — the Spectre ``.scs`` netlist generator.

This module is the repo-owned source of truth for the Cadence calibration
netlists (AT_4000TG AFE). It had no direct tests: the calibration flow only ran
it end-to-end on the ``flex`` server, so a formatting regression (wrong port
order, mangled analysis line, dropped device) would only surface as a puzzling
Spectre parse error far from here. These tests pin the *text contract* — device
cards, source/bias lines, analysis statements, and the header/devices/analyses
structure — with substring/regex anchors rather than a whole-file snapshot, so
they stay robust to cosmetic edits while catching real breakage.

Public interface under test:
  * ``gen_amp_netlist``   — AFE core DC/AC/noise testbench
  * ``gen_chopper_netlist`` — 8-PMOS chopper PSS/PAC/PNoise testbench
  * ``gen_runner``        — bash runner wrapping ``spectre`` with PSFASCII out

Findings recorded (NOT fixed — this is a test-only task):
  * ``_device_card`` formats W/L with ``:.0f``, so any sub-µm value silently
    rounds (``1e-15 -> 0``, ``100.7 -> 101``). Fine for the µm-integer W/L the
    solvers use, but a caller passing metres would get ``W=0``. Pinned by
    ``test_device_card_rounds_wl_to_integer_microns`` so the behavior is a
    documented contract, not an accident.
"""
import re

import pytest

from core.cadence_netlist import (gen_amp_netlist, gen_chopper_netlist,
                                   gen_runner)
from core.topology import AFE_TOPO

# A concrete AFE operating point (mirrors examples/afe_explore.json). Every
# device in AFE_TOPO must have an entry or the netlist raises KeyError.
_SIZES = {
    "M6": (2264, 78), "M7": (61365, 61), "M8": (61365, 61),
    "M9": (3175, 468), "M10": (3175, 468), "M11": (465, 66),
    "M12": (894, 85), "M13": (894, 85), "M14": (5224, 46), "M15": (5224, 46),
}
_BIAS = {"VDD": 40.0, "VCM": 30.65, "VB": 9.84, "VC": 16.0}


# ── gen_amp_netlist ───────────────────────────────────────────────────────────

def test_amp_netlist_header_block():
    scs = gen_amp_netlist(_SIZES, _BIAS)
    lines = scs.splitlines()
    # First three lines are the Spectre boilerplate header.
    assert lines[0].startswith("// AFE core")
    assert "generated by core.cadence_netlist" in lines[0]
    assert "simulator lang=spectre" in lines
    assert "global 0" in lines
    # parameters line carries every bias value verbatim.
    param = next(ln for ln in lines if ln.startswith("parameters "))
    assert "VDD=40.0" in param and "VCM=30.65" in param
    assert "VB=9.84" in param and "VC=16.0" in param
    # Model include + AHDL include both present.
    assert any("monte.scs" in ln and "section=typical" in ln for ln in lines)
    assert any("veriloga.va" in ln for ln in lines)


def test_amp_netlist_bias_sources():
    scs = gen_amp_netlist(_SIZES, _BIAS)
    # DC rail sources: VDD/VB/VC each a vsource referencing the parameter.
    assert re.search(r"^VDD_SRC \(VDD 0\) vsource dc=VDD$", scs, re.M)
    assert re.search(r"^VB_SRC\s+\(VB\s+0\) vsource dc=VB$", scs, re.M)
    assert re.search(r"^VC_SRC\s+\(VC\s+0\) vsource dc=VC$", scs, re.M)


def test_amp_netlist_differential_ac_sources():
    # The input pair (M7 +0.5, M8 -0.5) becomes vip/vin AC sources at VCM.
    scs = gen_amp_netlist(_SIZES, _BIAS, ac_drive=0.5)
    assert re.search(r"^vip_SRC \(vip 0\) vsource dc=VCM mag=0\.5$", scs, re.M)
    assert re.search(r"^vin_SRC \(vin 0\) vsource dc=VCM mag=-0\.5$", scs, re.M)
    # ac_drive scales both legs symmetrically.
    scs2 = gen_amp_netlist(_SIZES, _BIAS, ac_drive=0.25)
    assert "mag=0.25" in scs2 and "mag=-0.25" in scs2


def test_amp_netlist_device_cards_format_and_port_order():
    scs = gen_amp_netlist(_SIZES, _BIAS)
    # Every AFE device appears as a pmos_TFT card with W/L/NF fields.
    for name in _SIZES:
        w, l = _SIZES[name]
        pat = rf"^{name} \([^)]+\) pmos_TFT W={w:.0f} L={l:.0f} NF=1 "
        assert re.search(pat, scs, re.M), f"missing/malformed card for {name}"
    # pmos_TFT port order is (s d gate): topology M6 = (drain NET2, gate VB,
    # source VDD) -> printed (VDD NET2 VB), and GND resolves to node 0.
    assert re.search(r"^M6 \(VDD NET2 VB\) pmos_TFT ", scs, re.M)
    # The input pair's gate is swapped for the vip/vin AC node, not VCM.
    assert re.search(r"^M7 \(NET2 VOP vip\) pmos_TFT ", scs, re.M)
    assert re.search(r"^M8 \(NET2 VON vin\) pmos_TFT ", scs, re.M)
    # M14 source/drain both resolve to GND -> node 0.
    assert re.search(r"^M14 \(VFBN 0 0\) pmos_TFT ", scs, re.M)


def test_amp_netlist_load_caps_and_analyses():
    scs = gen_amp_netlist(_SIZES, _BIAS, fstart=0.02, fstop=5e3, dec=15)
    lines = scs.splitlines()
    # Load caps from the topology (VOP/VON to ground, 5 pF).
    assert any(re.match(r"^CL0 \(VOP 0\) capacitor c=5e-12$", ln) for ln in lines)
    assert any(re.match(r"^CL1 \(VON 0\) capacitor c=5e-12$", ln) for ln in lines)
    # Analysis statements: dcOp, ac, noise all present with the frequency args.
    assert any(ln.startswith("dcOp dc ") for ln in lines)
    assert re.search(r"^ac ac start=0\.02 stop=5000 dec=15 ", scs, re.M)
    assert re.search(r"^noiseAnal \(VOP VON\) noise start=0\.02 stop=5000 dec=15 ",
                     scs, re.M)
    # save line names the outputs and the AC drive nodes.
    assert re.search(r"^save VOP VON vip vin$", scs, re.M)
    # simulatorOptions present (the DC/AC tolerances block).
    assert any(ln.startswith("simulatorOptions options ") for ln in lines)


def test_amp_netlist_structure_partitions():
    """A structural (not snapshot) assertion: the netlist has a header block, a
    device block, and an analyses block, in that order."""
    scs = gen_amp_netlist(_SIZES, _BIAS)
    lines = scs.splitlines()
    idx_header = next(i for i, ln in enumerate(lines)
                      if ln.startswith("simulator lang=spectre"))
    idx_first_device = next(i for i, ln in enumerate(lines)
                            if re.match(r"^M6 \(", ln))
    idx_ac = next(i for i, ln in enumerate(lines) if ln.startswith("ac ac "))
    idx_save = next(i for i, ln in enumerate(lines) if ln.startswith("save "))
    # header < devices < analyses < save, strictly increasing.
    assert idx_header < idx_first_device < idx_ac < idx_save
    # Exactly the ten AFE devices are emitted as pmos_TFT cards.
    device_cards = [ln for ln in lines if re.match(r"^M\d+ \(.+\) pmos_TFT ", ln)]
    assert len(device_cards) == len(AFE_TOPO.devices) == 10


def test_amp_netlist_nf_dict_and_scalar():
    # nf as a per-device dict: only the named devices get the override.
    scs = gen_amp_netlist(_SIZES, _BIAS, nf={"M7": 4, "M8": 4})
    assert re.search(r"^M7 \(NET2 VOP vip\) pmos_TFT W=61365 L=61 NF=4 ", scs, re.M)
    assert re.search(r"^M6 \(VDD NET2 VB\) pmos_TFT W=2264 L=78 NF=1 ", scs, re.M)
    # nf as a scalar: applies to every device.
    scs2 = gen_amp_netlist(_SIZES, _BIAS, nf=8)
    assert scs2.count("NF=8") == 10


def test_amp_netlist_section_override():
    scs = gen_amp_netlist(_SIZES, _BIAS, section="mc_g")
    assert "section=mc_g" in scs
    assert "section=typical" not in scs


def test_amp_netlist_missing_device_size_raises():
    incomplete = dict(_SIZES)
    del incomplete["M9"]
    with pytest.raises(KeyError):
        gen_amp_netlist(incomplete, _BIAS)


# ── gen_chopper_netlist ───────────────────────────────────────────────────────

def test_chopper_netlist_header_and_params():
    scs = gen_chopper_netlist(_SIZES, _BIAS, f_chop=225.0, edge_time=20e-6)
    lines = scs.splitlines()
    assert lines[0].startswith("// 8-PMOS AFE chopper")
    param = next(ln for ln in lines if ln.startswith("parameters "))
    # Chopper params: bias + fchop (rounded int) + exact-fraction period + rise.
    assert "VDD=40.0" in param and "VCM=30.65" in param
    assert "fchop=225" in param and "Tper=1/225" in param and "Tr=2e-05" in param


def test_chopper_netlist_pac_stimulus_and_clocks():
    scs = gen_chopper_netlist(_SIZES, _BIAS)
    # Differential PAC stimulus uses pacmag (not mag); inverted leg via phase 180.
    assert re.search(r"^vinp \(vinp 0\) vsource dc=VCM pacmag=0\.5 pacphase=0$",
                     scs, re.M)
    assert re.search(r"^vinn \(vinn 0\) vsource dc=VCM pacmag=0\.5 pacphase=180$",
                     scs, re.M)
    # Two complementary pulse clocks (A starts low, B starts high).
    assert re.search(r"^VCLK_A \(CLK_A 0\) vsource type=pulse val0=0 val1=VDD ",
                     scs, re.M)
    assert re.search(r"^VCLK_B \(CLK_B 0\) vsource type=pulse val0=VDD val1=0 ",
                     scs, re.M)
    assert "period=Tper rise=Tr fall=Tr" in scs


def test_chopper_netlist_core_devices_and_commutators():
    scs = gen_chopper_netlist(_SIZES, _BIAS, switch_size=(5000, 30))
    # Core amp devices M6..M15 present as pmos_TFT with the chopper node names.
    assert re.search(r"^M7 \(NET2 AMP_OP INP\) pmos_TFT W=61365 L=61 NF=1 ", scs, re.M)
    assert re.search(r"^M8 \(NET2 AMP_ON INN\) pmos_TFT W=61365 L=61 NF=1 ", scs, re.M)
    # Eight commutator switches, all at the switch W/L, none omitted.
    sw_names = ["CH_SW_INP_A", "CH_SW_INN_A", "CH_SW_INP_B", "CH_SW_INN_B",
                "CH_SW_OUTP_A", "CH_SW_OUTN_A", "CH_SW_OUTP_B", "CH_SW_OUTN_B"]
    for name in sw_names:
        assert re.search(rf"^{name} \([^)]+\) pmos_TFT W=5000 L=30 NF=1 ", scs, re.M), name
    # Input-chop cross wiring: A-phase straight, B-phase crossed.
    assert re.search(r"^CH_SW_INP_A \(vinp INP CLK_A\) ", scs, re.M)
    assert re.search(r"^CH_SW_INP_B \(vinp INN CLK_B\) ", scs, re.M)


def test_chopper_netlist_demod_and_analyses():
    scs = gen_chopper_netlist(_SIZES, _BIAS, f_chop=225.0, harms=20,
                              pac_stop=200.0, pnoise_stop=200.0, maxsideband=10,
                              tstab="25m")
    # Output demod RC low-pass to baseband voutp_f/voutn_f.
    assert re.search(r"^RLP_P \(VOP voutp_f\) resistor r=1e6$", scs, re.M)
    assert re.search(r"^CBB_P \(voutp_f 0\) capacitor c=680p$", scs, re.M)
    # PSS/PAC/PNoise analysis statements.
    assert re.search(r"^pss pss fund=fchop harms=20 tstab=25m ", scs, re.M)
    assert re.search(r"^pac pac start=0\.01 stop=200 maxsideband=10 ", scs, re.M)
    assert re.search(r"^pnoise \(voutp_f voutn_f\) pnoise start=0\.05 stop=200 "
                     r"dec=10 maxsideband=10 ", scs, re.M)
    assert re.search(r"^save vinp vinn voutp_f voutn_f VOP VON AMP_OP AMP_ON$",
                     scs, re.M)


def test_chopper_netlist_structure_partitions():
    scs = gen_chopper_netlist(_SIZES, _BIAS)
    lines = scs.splitlines()
    idx_header = next(i for i, ln in enumerate(lines)
                      if ln.startswith("simulator lang=spectre"))
    idx_first_device = next(i for i, ln in enumerate(lines)
                            if re.match(r"^M6 \(", ln))
    idx_first_switch = next(i for i, ln in enumerate(lines)
                            if ln.startswith("CH_SW_INP_A "))
    idx_pss = next(i for i, ln in enumerate(lines) if ln.startswith("pss pss "))
    idx_save = next(i for i, ln in enumerate(lines) if ln.startswith("save "))
    assert idx_header < idx_first_device < idx_first_switch < idx_pss < idx_save
    # Ten core devices + eight commutators = eighteen pmos_TFT cards.
    device_cards = [ln for ln in lines if " pmos_TFT " in ln]
    assert len(device_cards) == 18


def test_chopper_netlist_fchop_rounds_to_int():
    # f_chop is rounded to the nearest integer for the fchop param / period.
    scs = gen_chopper_netlist(_SIZES, _BIAS, f_chop=224.6)
    assert "fchop=225" in scs and "Tper=1/225" in scs


def test_chopper_netlist_switch_size_and_maxsideband():
    scs = gen_chopper_netlist(_SIZES, _BIAS, switch_size=(3000, 20),
                              maxsideband=15)
    assert re.search(r"^CH_SW_INP_A \([^)]+\) pmos_TFT W=3000 L=20 NF=1 ", scs, re.M)
    # maxsideband threads to both PAC and PNoise.
    assert scs.count("maxsideband=15") == 2


# ── gen_runner ────────────────────────────────────────────────────────────────

def test_runner_basic_shape():
    r = gen_runner("amp.scs", rundir="/home/me/run")
    assert r.startswith("#!/bin/bash")
    assert "export LM_LICENSE_FILE=" in r
    assert "source /eda/cadence" in r and "SPECTRE" in r
    assert "cd /home/me/run" in r
    # Default raw/log stems derive from the scs name.
    assert "spectre amp.scs" in r
    assert "+log amp.log" in r and "-raw ./amp.raw" in r
    assert "psfascii" in r
    assert r.rstrip().endswith("echo ALL_DONE")


def test_runner_explicit_raw_and_log():
    r = gen_runner("chopper.scs", rundir="/tmp/x", raw="out.raw", log="run.log")
    assert "spectre chopper.scs" in r
    assert "+log run.log" in r and "-raw ./out.raw" in r


def test_runner_stem_strips_only_last_extension():
    # A dotted stem keeps everything before the final extension.
    r = gen_runner("amp.v2.scs", rundir="/tmp/x")
    assert "+log amp.v2.log" in r and "-raw ./amp.v2.raw" in r


# ── formatting-edge / recorded-behavior checks ────────────────────────────────

def test_device_card_rounds_wl_to_integer_microns():
    """RECORDED BEHAVIOR (not a bug to fix): W/L use ``:.0f`` formatting, so
    fractional/sub-µm sizes are silently rounded. A caller passing SI metres
    (e.g. 1e-15) would emit ``W=0``. The solvers use integer-µm W/L, so this is
    safe in practice, but the rounding is pinned here so it can't drift unnoticed.
    """
    tiny = dict(_SIZES)
    tiny["M6"] = (1e-15, 2e-15)      # sub-µm -> rounds to 0
    tiny["M7"] = (100.7, 50.4)       # fractional µm -> nearest integer
    scs = gen_amp_netlist(tiny, _BIAS)
    assert re.search(r"^M6 \(VDD NET2 VB\) pmos_TFT W=0 L=0 NF=1 ", scs, re.M)
    assert re.search(r"^M7 \(NET2 VOP vip\) pmos_TFT W=101 L=50 NF=1 ", scs, re.M)


def test_amp_and_chopper_netlists_are_strings_without_trailing_none():
    # Both generators return a single joined string (no None sentinels leaked in).
    amp = gen_amp_netlist(_SIZES, _BIAS)
    chop = gen_chopper_netlist(_SIZES, _BIAS)
    assert isinstance(amp, str) and isinstance(chop, str)
    assert "None" not in amp and "None" not in chop
