"""Spectre netlist generation for the Cadence calibration loop.

Emits ``.scs`` netlists for the AT_4000TG AFE straight from the repo topology and
the same ``sizes``/``bias`` the local solvers use, so the Cadence reference and the
Python result describe the *same* circuit. This is the repo-owned source of truth
for verification netlists (it supersedes the old hand-maintained glue under
``~/Documents/EE/Flexible/Project/code``).

Two testbenches:
    amp     — AFE core (M6–M15, no chopper) -> DC / AC / noise
    chopper — AFE core + 8 commutators + clocks -> PSS / PAC / PNoise (LPTV)

The pmos_TFT model port order is ``(s d gate)``; the topology stores devices as
``(name, drain, gate, source)``. Clock/PAC details follow the verified chopper
recipe (period exactly ``1/fchop``, ``pacmag`` not ``mag``, ``maxsideband>=10``).
"""
from __future__ import annotations

from .topology import AFE_TOPO

# pmos_TFT model card shared by every device (matches tools/calibrate_switch.py and
# the AT_4000TG reference netlists). Only W/L/NF vary per instance.
_MODEL = "VT=-3.03 Roff=1 Reg=1 C1=37.5 C2=50 C3=35 C4=35 Ci=2.4 kv=1 kh=1"
_MODEL_INC = (
    'include "/cadappl_sde/iclibs/AT_4000TG/AT_4000TG/monte.scs" section={section}\n'
    'ahdl_include "/cadappl_sde/iclibs/AT_4000TG/AT_4000TG/pmos_TFT/veriloga/veriloga.va"'
)


def _nf(nf, name):
    if isinstance(nf, dict):
        return int(nf.get(name, 1))
    return int(nf) if nf else 1


def _node_resolver(topo):
    """Map topology node names to Spectre node names: any rail pinned to a constant
    0 V (e.g. ``GND``) becomes the global ground ``0``; everything else is unchanged."""
    ground = {n for n, v in topo.rails.items() if isinstance(v, (int, float)) and v == 0.0}

    def n(node):
        return "0" if node in ground else node
    return n


def _device_card(name, drain, gate, source, w, l, nf, n=lambda x: x):
    # pmos_TFT ports are (s d gate); topology gives (drain, gate, source).
    return (f"{name} ({n(source)} {n(drain)} {n(gate)}) pmos_TFT "
            f"W={w:.0f} L={l:.0f} NF={nf} {_MODEL}")


def gen_amp_netlist(sizes, bias, *, nf=None, topo=AFE_TOPO, section="typical",
                    ac_drive=0.5, fstart=0.01, fstop=1e4, dec=20) -> str:
    """AFE core (no chopper) DC/AC/noise netlist.

    The input pair gates (``M7``/``M8``) are split into differential AC sources
    ``vip``/``vin`` at common mode ``VCM`` with ``mag=+/-ac_drive``; outputs are the
    two solved output nodes. Mirrors ``ac_solve``/``noise_analysis`` exactly."""
    out_p, out_n = topo.outputs
    drive_dev = dict(topo.input_drives)            # {M7: +0.5, M8: -0.5}
    if len(drive_dev) != 2:
        raise ValueError("amp netlist needs exactly two differentially driven gates")
    n = _node_resolver(topo)                        # GND -> 0
    lines = [
        "// AFE core (non-chopper) DC/AC/noise — generated by core.cadence_netlist",
        "simulator lang=spectre",
        "global 0",
        f"parameters VDD={bias['VDD']} VCM={bias['VCM']} VB={bias['VB']} VC={bias['VC']}",
        _MODEL_INC.format(section=section),
        "",
        "VDD_SRC (VDD 0) vsource dc=VDD",
        "VB_SRC  (VB  0) vsource dc=VB",
        "VC_SRC  (VC  0) vsource dc=VC",
    ]
    # Differential AC input sources at the two driven gates (named vip/vin).
    gate_node = {}
    for dev, mag in drive_dev.items():
        node = "vip" if mag > 0 else "vin"
        gate_node[dev] = node
        lines.append(f"{node}_SRC ({node} 0) vsource dc=VCM mag={ac_drive if mag > 0 else -ac_drive}")
    lines.append("")
    for name, drain, gate, source in topo.devices:
        g = gate_node.get(name, gate)              # swap VCM gate -> vip/vin for the pair
        w, l = sizes[name]
        lines.append(_device_card(name, drain, g, source, w, l, _nf(nf, name), n))
    lines.append("")
    for i, (a, b, c) in enumerate(topo.load_caps):
        lines.append(f"CL{i} ({n(a)} {n(b)}) capacitor c={c}")
    lines += [
        "",
        "simulatorOptions options reltol=1e-4 vabstol=1e-7 iabstol=1e-13 "
        "temp=27 tnom=27 gmin=1e-12",
        "dcOp dc maxiters=150 annotate=status",
        f"ac ac start={fstart} stop={fstop:g} dec={dec} annotate=status",
        f"noiseAnal ({out_p} {out_n}) noise start={fstart} stop={fstop:g} dec={dec} "
        "annotate=status",
        f"save {out_p} {out_n} vip vin",
        "",
    ]
    return "\n".join(lines)


def gen_chopper_netlist(sizes, bias, *, switch_size=(5000, 30), nf=None,
                        f_chop=225.0, section="typical", edge_time=20e-6,
                        pac_stop=200.0, pnoise_stop=200.0, harms=20, tstab="25m",
                        maxsideband=10) -> str:
    """8-PMOS AFE chopper PSS/PAC/PNoise netlist (LPTV).

    Differential input ``vinp``/``vinn`` at common mode ``VCM`` carry the PAC stimulus
    (``pacmag=0.5``, the inverted leg via ``pacphase=180`` — Spectre rejects negative
    ``pacmag``). Outputs are demodulated to baseband ``voutp_f``/``voutn_f`` through an
    RC low-pass. Clock period is the exact fraction ``1/f_chop`` and ``maxsideband>=10``
    on both PAC and PNoise — the two failure modes called out in the chopper recipe."""
    sw_w, sw_l = switch_size
    swc = (f"W={sw_w:.0f} L={sw_l:.0f} NF=1 {_MODEL}")
    fchop = f"{int(round(f_chop))}"
    L = [
        "// 8-PMOS AFE chopper PSS/PAC/PNoise — generated by core.cadence_netlist",
        "simulator lang=spectre",
        "global 0",
        f"parameters VDD={bias['VDD']} VCM={bias['VCM']} VB={bias['VB']} VC={bias['VC']} "
        f"fchop={fchop} Tper=1/{fchop} Tr={edge_time:g}",
        _MODEL_INC.format(section=section),
        "",
        "VDD_SRC (VDD 0) vsource dc=VDD",
        "VB_SRC  (VB  0) vsource dc=VB",
        "VC_SRC  (VC  0) vsource dc=VC",
        "// differential PAC stimulus (pacmag, not mag; invert via pacphase=180)",
        "vinp (vinp 0) vsource dc=VCM pacmag=0.5 pacphase=0",
        "vinn (vinn 0) vsource dc=VCM pacmag=0.5 pacphase=180",
        "VCLK_A (CLK_A 0) vsource type=pulse val0=0 val1=VDD delay=Tper/2 width=Tper/2 "
        "period=Tper rise=Tr fall=Tr",
        "VCLK_B (CLK_B 0) vsource type=pulse val0=VDD val1=0 delay=Tper/2 width=Tper/2 "
        "period=Tper rise=Tr fall=Tr",
        "",
    ]

    def dev(name, s, d, g, w, l, n=1):
        return f"{name} ({s} {d} {g}) pmos_TFT W={w:.0f} L={l:.0f} NF={n} {_MODEL}"

    # Core amp (pmos_TFT port order s d g). Input pair gates are the chopped nodes INP/INN;
    # outputs are AMP_OP/AMP_ON (then commutated to VOP/VON).
    core = [
        ("M6", "VDD", "NET2", "VB"), ("M7", "NET2", "AMP_OP", "INP"),
        ("M8", "NET2", "AMP_ON", "INN"), ("M9", "AMP_OP", "0", "VFBP"),
        ("M10", "AMP_ON", "0", "VFBN"), ("M11", "VDD", "NET20", "VC"),
        ("M12", "NET20", "VFBN", "AMP_OP"), ("M13", "NET20", "VFBP", "AMP_ON"),
        ("M14", "VFBN", "0", "0"), ("M15", "VFBP", "0", "0"),
    ]
    for name, s, d, g in core:
        w, l = sizes[name]
        L.append(dev(name, s, d, g, w, l, _nf(nf, name)))
    L.append("")
    # Eight commutators: input chop (vinp/vinn -> INP/INN) and output chop (AMP -> VOP/VON).
    sw = [
        ("CH_SW_INP_A", "vinp", "INP", "CLK_A"), ("CH_SW_INN_A", "vinn", "INN", "CLK_A"),
        ("CH_SW_INP_B", "vinp", "INN", "CLK_B"), ("CH_SW_INN_B", "vinn", "INP", "CLK_B"),
        ("CH_SW_OUTP_A", "AMP_OP", "VOP", "CLK_A"), ("CH_SW_OUTN_A", "AMP_ON", "VON", "CLK_A"),
        ("CH_SW_OUTP_B", "AMP_OP", "VON", "CLK_B"), ("CH_SW_OUTN_B", "AMP_ON", "VOP", "CLK_B"),
    ]
    for name, s, d, g in sw:
        L.append(f"{name} ({s} {d} {g}) pmos_TFT {swc}")
    L += [
        "",
        "CLP (VOP 0) capacitor c=5p",
        "CLN (VON 0) capacitor c=5p",
        "// demodulate chopped output to baseband voutp_f/voutn_f",
        "RLP_P (VOP voutp_f) resistor r=1e6",
        "RLP_N (VON voutn_f) resistor r=1e6",
        "CBB_P (voutp_f 0) capacitor c=680p",
        "CBB_N (voutn_f 0) capacitor c=680p",
        "",
        "simulatorOptions options reltol=1e-5 vabstol=1e-8 iabstol=1e-13 temp=27 tnom=27 "
        "gmin=1e-12 maxnotes=5 maxwarns=5",
        f"pss pss fund=fchop harms={harms} tstab={tstab} errpreset=conservative annotate=status",
        f"pac pac start=0.01 stop={pac_stop:g} maxsideband={maxsideband} annotate=status",
        f"pnoise (voutp_f voutn_f) pnoise start=0.05 stop={pnoise_stop:g} dec=10 "
        f"maxsideband={maxsideband} annotate=status",
        "save vinp vinn voutp_f voutn_f VOP VON AMP_OP AMP_ON",
        "",
    ]
    return "\n".join(L)


RUNNER = """#!/bin/bash
export LM_LICENSE_FILE=5280@ankaramy.ele.tue.nl
source /eda/cadence/2024-25/scripts/SPECTRE_24.10.078_RHELx86.sh
cd {rundir}
spectre {scs} +escchars +log {log} -format psfascii -raw ./{raw} 2>&1 | tail -4
echo ALL_DONE
"""


def gen_runner(scs_name, *, rundir, raw=None, log=None) -> str:
    """A bash runner that sets the license, sources the Spectre-only env, and runs
    the netlist with PSFASCII output. Pipe it through ``ssh flex 'bash -s'``."""
    stem = scs_name.rsplit(".", 1)[0]
    return RUNNER.format(rundir=rundir, scs=scs_name,
                         raw=raw or f"{stem}.raw", log=log or f"{stem}.log")
