"""Per-device build/resolve layer: model_types / NF / corner / device_kwargs ->
:class:`TransistorModel` instances.

Turns the per-device inputs each solver already carries (sizes, NF, corner,
model_types, device_kwargs) into concrete device instances, and owns the two
corner mechanisms this project supports: the OTFT continuous-PVT shift data
(:data:`CORNERS`) applied by the solvers, and the silicon discrete-corner
routing (:func:`apply_silicon_corner`) that stamps a corner name onto extracted
silicon device cards. This is a leaf device layer — it depends only on
:mod:`.device_model`, never on any solver or workflow module.
"""
from .device_model import create_device, get_default_model_type

# Global process corners (pvt0 = -3·0.0753, pbeta0 = -15·0.036 for slow).
# Numbers come from the AT4000TG PDK monte.scs sections.
CORNERS = {
    "typical": {"pvt0": 0.0, "pbeta0": 0.0},
    "slow": {"pvt0": -0.2259, "pbeta0": -0.54},
    "fast": {"pvt0": +0.2259, "pbeta0": +0.54},
}


def dev_corner(corner, name):
    """Resolve the model-shift dict for one device.

    corner may be:
      - None / {}                              -> nominal (no shift)
      - 'typical' / 'slow' / 'fast'            -> named process corner
      - flat dict {'pvt0':.., 'pbeta0':..}     -> GLOBAL shift, same for all devices
                                                  (process corner)
      - per-device map {'M7':{...}, 'M8':{...}}-> PER-DEVICE shift (mismatch:
                                                  each device its own mvt0/mbeta0)
    """
    if not corner:
        return {}
    if isinstance(corner, str):
        if corner not in CORNERS:
            raise ValueError(f"Unknown process corner {corner!r}; expected one of {sorted(CORNERS)}")
        return CORNERS[corner]
    if any(isinstance(v, dict) for v in corner.values()):     # per-device map
        return corner.get(name, {})
    return corner                                             # global shift


def is_per_device_corner(corner):
    if not corner or isinstance(corner, str):
        return False
    return any(isinstance(v, dict) for v in corner.values())


def dev_nf(nf, name):
    """Resolve NF (number of fingers) for one device. nf may be None (->1),
    an int (global), or a per-device map {'M7':120,...} (missing -> 1).
    NF doesn't change Idc/gm (current ∝ total W/L) but DOES change the gate
    capacitances (Cgs/Cgd via finger geometry), hence BW and the cap part of noise."""
    if not nf:
        return 1
    if isinstance(nf, dict):
        return int(nf.get(name, 1))
    return int(nf)


def build_devices(sizes, *, nf=None, corner=None, topo, model_types=None,
                  device_kwargs=None):
    """Create ``{name: TransistorModel}`` for every transistor in *topo*.

    Shared factory used by all solvers instead of repeating the same
    device-creation dict comprehension in each file.  Resolves NF per-device
    via :func:`dev_nf` and applies corner shifts via :func:`dev_corner`.

    ``model_types`` optionally maps a device name to a model-registry key (e.g.
    ``"sky130.nmos"``) for mixed-process / complementary testbenches; unnamed
    devices fall back to the default PDK.  ``device_kwargs`` passes extra
    per-device constructor kwargs (e.g. ``{"vb": 1.8}`` for a PMOS bulk).  Both
    default to empty, so the OTFT path is unchanged.
    """
    model_types = model_types or {}
    device_kwargs = device_kwargs or {}
    return {
        name: create_device(
            model_types.get(name, get_default_model_type()),
            W=sizes[name][0], L=sizes[name][1],
            NF=dev_nf(nf, name), **dev_corner(corner, name),
            **device_kwargs.get(name, {}),
        )
        for name, *_ in topo.devices
    }


def get_ss_params(W, L, Vs, Vd, Vg, corner=None, nf=1, dev_inst=None):
    """Small-signal parameters at a DC operating point.

    gm/gds are the *terminal* values, extracted by finite-differencing the full
    terminal current get_Idc (which solves the OTFT internal contact nodes).
    The channel gm from _eval_channel is degenerated by the contact resistance;
    Spectre's AC sees the terminal value. Using terminal gm matches Cadence to
    <0.05 dB / <0.1 Hz across the band; channel gm was 0.8 dB / 18 Hz off.

    corner: optional dict of model process shifts, e.g. {'pvt0':.., 'pbeta0':..}.
    dev_inst: optional pre-built :class:`TransistorModel` instance to reuse
        (warm-start cache).

    Thin adapter — delegates to :meth:`TransistorModel.get_ss_params`.
    """
    t = dev_inst if dev_inst is not None else create_device(
        get_default_model_type(), W=W, L=L, NF=nf, **(corner or {}))
    return t.get_ss_params(Vs, Vd, Vg)


# Silicon discrete process corners are baked into the extracted device card (a
# per-device constructor kwarg), a different mechanism from the OTFT continuous PVT
# shift the solvers apply via ``corner=``. :func:`apply_silicon_corner` keeps the two
# separate: a silicon corner name is routed onto silicon devices, an OTFT corner is
# left for the solver shift path. SKY130 uses tt/ss/ff/sf/fs; FreePDK45 ships
# nom/ss/ff card directories (nom == typical).
SKY130_CORNERS = frozenset({"tt", "ss", "ff", "sf", "fs"})
SILICON_CORNERS = SKY130_CORNERS | {"nom"}
_SILICON_PREFIXES = ("sky130", "freepdk45")


def apply_silicon_corner(model_types, device_kwargs, corner):
    """Route a silicon corner onto silicon devices; leave OTFT corners for the solver.

    Returns ``(device_kwargs, solver_corner)``. When ``corner`` names a silicon corner
    (SKY130 ``tt/ss/ff/sf/fs`` or FreePDK45 ``nom/ss/ff``), it is stamped as
    ``corner=<name>`` on every ``sky130.*`` / ``freepdk45.*`` device's kwargs and the
    solver corner is cleared (``None``) — silicon ignores the OTFT PVT shift. Otherwise
    (an OTFT corner name / shift-map / ``None``) the device kwargs pass through unchanged
    and ``corner`` is returned for the solver path. A circuit is single-process, so the
    shared ``ss``/``ff`` names route onto whichever silicon family the devices declare."""
    if not isinstance(corner, str) or corner not in SILICON_CORNERS:
        return device_kwargs, corner
    mt = model_types or {}
    dk = {name: dict(kw) for name, kw in (device_kwargs or {}).items()}
    for name, model in mt.items():
        if str(model).startswith(_SILICON_PREFIXES):
            dk.setdefault(name, {})["corner"] = corner
    return dk, None
