//! co-bsim4 — Rust host for the Berkeley BSIM4.5 compact model (R2).
//!
//! This crate is the Rust port of
//! `circuitopt/compact_models/bsim4/native_src/host.c`. `build.rs` compiles the
//! *unmodified* vendored Berkeley BSIM4.5 C (the same translation units
//! `native.py` builds, minus `host.c`) into a static archive and bindgens the
//! shared headers; the Rust below reimplements the host adapter layer — the
//! parameter binding, internal-node reduction, the terminal I/G/Q/C extraction,
//! and the noise combination — with the same arithmetic and operation order as
//! `host.c`, so the results match bit-for-bit (validated against the frozen
//! v1.4.0 golden corpus to 1e-13, and directly against the C `cc` backend).
//!
//! Threading: every entry that touches the vendor C takes a single crate-global
//! `Mutex`. The Berkeley sources carry ~128 file-scope mutable globals plus the
//! process-global front-end pointers wired up here, so even distinct device
//! handles must be evaluated under mutual exclusion (R2 uses a global lock; a
//! TLS-based scheme is deferred).

#![allow(clippy::missing_safety_doc)]
// This crate is a thin, faithful port of a C translation unit: nearly every
// function is `unsafe` and dereferences raw FFI pointers. Requiring an inner
// `unsafe {}` around each such op (the edition-2024 default) would bury the
// port in noise without adding signal, so we opt the whole crate out.
#![allow(unsafe_op_in_unsafe_fn)]
// The dense solves and the terminal reductions mirror host.c's explicit index
// loops verbatim so the floating-point evaluation order — and therefore the
// result bits — match the reference C. Rewriting them as iterator chains would
// obscure that correspondence, so `needless_range_loop` is opted out crate-wide.
#![allow(clippy::needless_range_loop)]

use std::ffi::CStr;
use std::os::raw::{c_char, c_int, c_long, c_void};
use std::ptr::{addr_of, addr_of_mut, null_mut};
use std::sync::atomic::{AtomicPtr, Ordering};
use std::sync::{Mutex, MutexGuard};

/// FFI surface generated by bindgen from `csrc/wrapper.h` (see `build.rs`).
mod ffi {
    #![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
    #![allow(dead_code, clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

// ---------------------------------------------------------------------------
// Constants (mirrors the `#define`s host.c relies on; values pinned from the
// vendored ngspice headers so the port does not depend on macro emission).
// ---------------------------------------------------------------------------

/// Stable four-terminal C ABI version, surfaced through `co_bsim4_abi_version`.
pub const ABI_VERSION: u32 = 1;

const CO_MAX_NODES: usize = 24;
const CO_STATES: usize = 256;
const CO_TERMINALS: usize = 4;
const CO_MAX_INTERNAL: usize = 7;
const CO_MAX_NOISE_SOURCES: usize = 16;
// host.c uses the literal 3.14159265358979323846, which rounds to this f64.
const CO_PI: f64 = std::f64::consts::PI;

// ngspice error codes (iferrmsg.h)
const OK: c_int = 0;
const E_PANIC: c_int = 1;
const E_BADPARM: c_int = 7;
const E_NOMEM: c_int = 8;
const E_UNSUPP: c_int = 10;
const E_PARMVAL: c_int = 11;
const E_NOCHANGE: c_int = 13;
const E_NOTFOUND: c_int = 14;

// IFparm dataType bits (ifsim.h)
const IF_FLAG: c_int = 0x1;
const IF_INTEGER: c_int = 0x2;
const IF_REAL: c_int = 0x4;
const IF_VARTYPES: c_int = 0x80ff;

// CKTmode flags (cktdefs.h)
const MODEDCOP: c_long = 0x10;
const MODEINITFLOAT: c_long = 0x100;
const MODEINITSMSIG: c_long = 0x800;

// node type + noise (cktdefs.h / noisedef.h / bsim4v5def.h)
const SP_VOLTAGE: c_int = 3;
const N_DENS: c_int = 1;
const N_CALC: c_int = 2;
const SHOTNOISE: c_int = 1;
const THERMNOISE: c_int = 2;
const N_GAIN: c_int = 3;
const BSIM4V5_FLNOIZ: c_int = 9;

// State-vector offsets relative to the instance's `BSIM4v5states` base index.
// In the vendor headers these are object-like macros (e.g.
// `#define BSIM4v5qd BSIM4v5states + 15`); bindgen does not surface them as
// struct fields, so the host reconstructs `state0[instance.BSIM4v5states + N]`.
const OFF_QB: c_int = 11;
const OFF_QG: c_int = 13;
const OFF_QD: c_int = 15;
const OFF_QBS: c_int = 19;
const OFF_QBD: c_int = 21;
const OFF_QS: c_int = 28;

const MODEL_NAME: &CStr = c"circuitopt_bsim4";
const INSTANCE_NAME: &CStr = c"m1";

// ---------------------------------------------------------------------------
// Host state layout (host.c `CoBsim4`). The embedded vendor structs come from
// bindgen so their layout matches the compiled C; the rest is host bookkeeping.
// The whole struct is only ever seen by this crate — the vendor sees pointers
// to `model` / `instance` / `ckt` — so its precise byte layout need only be
// self-consistent for the `CKTmkVolt` recovery via `offset_of!`.
// ---------------------------------------------------------------------------

#[repr(C)]
struct MatrixFrame {
    value: [[[f64; 2]; CO_MAX_NODES]; CO_MAX_NODES],
}

#[repr(C)]
#[derive(Clone, Copy)]
struct CoNoiseSource {
    index: c_int,
    node1: c_int,
    node2: c_int,
    density: f64,
}

#[repr(C)]
pub struct CoBsim4 {
    model: ffi::BSIM4v5model,
    instance: ffi::BSIM4v5instance,
    ckt: ffi::CKTcircuit,
    matrix: MatrixFrame,
    rhs: [f64; CO_MAX_NODES],
    rhs_old: [f64; CO_MAX_NODES],
    irhs: [f64; CO_MAX_NODES],
    state0: [f64; CO_STATES],
    state1: [f64; CO_STATES],
    nodes: [*mut ffi::CKTnode; CO_MAX_NODES],
    noise_sources: [CoNoiseSource; CO_MAX_NOISE_SOURCES],
    noise_source_count: c_int,
    setup_done: c_int,
}

// ---------------------------------------------------------------------------
// Crate-global vendor lock.
// ---------------------------------------------------------------------------

static VENDOR_LOCK: Mutex<()> = Mutex::new(());

#[inline]
fn lock() -> MutexGuard<'static, ()> {
    // Poisoning only signals a prior panic; the vendor scratch is reset at the
    // top of every evaluation, so recovering the guard is safe.
    VENDOR_LOCK
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
}

// ---------------------------------------------------------------------------
// Process-global front-end symbols the vendor C references.
//
// `AtomicPtr<T>` has the same in-memory representation as `*mut T`, so these
// `#[unsafe(no_mangle)]` statics present exactly the pointer-shaped symbols the vendor
// declares `extern` (`ft_curckt`, `SPfrontEnd`, `slogp`); they are populated
// once, under the lock, before any vendor call reads them.
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub static ft_curckt: AtomicPtr<ffi::circ> = AtomicPtr::new(null_mut());
#[unsafe(no_mangle)]
pub static SPfrontEnd: AtomicPtr<ffi::IFfrontEnd> = AtomicPtr::new(null_mut());
#[unsafe(no_mangle)]
pub static slogp: AtomicPtr<c_void> = AtomicPtr::new(null_mut());

// Berkeley physical constants (const.h `extern double`), read by b4v5temp.c /
// b4v5ld.c. host.c defined CONSTroot2 as 1.4142135623730950488, which rounds to
// the same f64 as `SQRT_2`; CONSTvt0 is pinned to host.c's literal.
#[unsafe(no_mangle)]
pub static CONSTroot2: f64 = std::f64::consts::SQRT_2;
#[unsafe(no_mangle)]
pub static CONSTvt0: f64 = 0.025_864_19;

/// Device currently collecting noise sources (host.c `co_active_noise_device`).
/// Set/cleared under the lock around the vendor noise call; the vendor invokes
/// `CircuitOptBsim4NoiseSource` synchronously on the same thread.
static ACTIVE_NOISE_DEVICE: AtomicPtr<CoBsim4> = AtomicPtr::new(null_mut());

/// No-op error sink (host.c `co_errorf`). The vendor front end declares
/// `IFerrorf` as variadic `void (*)(int, const char*, ...)`; this callee simply
/// ignores every argument, which is ABI-safe on the supported targets (extra
/// variadic arguments live in registers/stack the callee never reads).
extern "C" fn co_errorf(_level: c_int, _fmt: *const c_char) {}

/// Wire up the process-global front end exactly once, under the lock.
unsafe fn ensure_frontend() {
    if !SPfrontEnd.load(Ordering::Acquire).is_null() {
        return;
    }
    // Front end with only the error sink populated.
    let mut frontend: Box<ffi::IFfrontEnd> = Box::new(std::mem::zeroed());
    let sink: unsafe extern "C" fn(c_int, *const c_char, ...) =
        std::mem::transmute(co_errorf as extern "C" fn(c_int, *const c_char));
    frontend.IFerrorf = Some(sink);
    SPfrontEnd.store(Box::into_raw(frontend), Ordering::Release);

    // Front-end circuit + task: `ft_curckt->ci_curTask->jobs` is walked by
    // b4v5set.c (an empty list here).
    let circ_ptr = Box::into_raw(Box::new(std::mem::zeroed::<ffi::circ>()));
    let task_ptr = Box::into_raw(Box::new(std::mem::zeroed::<ffi::TSKtask>()));
    (*task_ptr).jobs = null_mut();
    (*circ_ptr).ci_curTask = task_ptr;
    ft_curckt.store(circ_ptr, Ordering::Release);
}

// ---------------------------------------------------------------------------
// Shim symbols the vendor C links against (host.c). Each is `#[unsafe(no_mangle)]`; the
// vendor archive's undefined references keep them in the final link.
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub unsafe extern "C" fn tmalloc(size: usize) -> *mut c_void {
    libc::calloc(1, size)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn trealloc(ptr: *mut c_void, size: usize) -> *mut c_void {
    libc::realloc(ptr, size)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn txfree(ptr: *mut c_void) {
    libc::free(ptr);
}

/// ngspice `bool` is `int`; return FALSE (no runtime variables).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn cp_getvar(
    _name: *mut c_char,
    _type: c_int,
    _retval: *mut c_void,
) -> c_int {
    0
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn SMPmakeElt(
    matrix: *mut ffi::SMPmatrix,
    row: c_int,
    col: c_int,
) -> *mut f64 {
    if row < 0 || row >= CO_MAX_NODES as c_int || col < 0 || col >= CO_MAX_NODES as c_int {
        return null_mut();
    }
    let dense = matrix as *mut MatrixFrame;
    addr_of_mut!((*dense).value[row as usize][col as usize][0])
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn CKTmkVolt(
    ckt: *mut ffi::CKTcircuit,
    result: *mut *mut ffi::CKTnode,
    _basename: ffi::IFuid,
    _suffix: *mut c_char,
) -> c_int {
    let device = (ckt as *mut u8).sub(std::mem::offset_of!(CoBsim4, ckt)) as *mut CoBsim4;
    (*ckt).CKTmaxEqNum += 1;
    let number = (*ckt).CKTmaxEqNum;
    if number >= CO_MAX_NODES as c_int {
        return E_NOMEM;
    }
    let node = libc::calloc(1, std::mem::size_of::<ffi::CKTnode>()) as *mut ffi::CKTnode;
    if node.is_null() {
        return E_NOMEM;
    }
    (*node).number = number;
    (*node).type_ = SP_VOLTAGE;
    (*device).nodes[number as usize] = node;
    *result = node;
    OK
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn CKTinst2Node(
    _ckt: *mut ffi::CKTcircuit,
    _instance: *mut c_void,
    _terminal: c_int,
    _node: *mut *mut ffi::CKTnode,
    _name: *mut ffi::IFuid,
) -> c_int {
    E_NOTFOUND
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn CKTdltNNum(_ckt: *mut ffi::CKTcircuit, _number: c_int) -> c_int {
    OK
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn NIintegrate(
    ckt: *mut ffi::CKTcircuit,
    geq: *mut f64,
    ceq: *mut f64,
    _cap: f64,
    state: c_int,
) -> c_int {
    let s = state as usize;
    let state0 = (*ckt).CKTstates[0];
    let state1 = (*ckt).CKTstates[1];
    *geq = (*ckt).CKTag[0];
    *state0.add(s + 1) = (*ckt).CKTag[0] * *state0.add(s) + (*ckt).CKTag[1] * *state1.add(s);
    *ceq = *state0.add(s + 1);
    OK
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn NevalSrc(
    noise: *mut f64,
    ln_noise: *mut f64,
    ckt: *mut ffi::CKTcircuit,
    r#type: c_int,
    _node1: c_int,
    _node2: c_int,
    parameter: f64,
) {
    if r#type == THERMNOISE {
        *noise = 4.0 * 1.380_649e-23 * (*ckt).CKTtemp * parameter;
    } else if r#type == SHOTNOISE {
        *noise = 2.0 * 1.602_176_634e-19 * parameter.abs();
    } else if r#type == N_GAIN {
        *noise = 1.0;
    } else {
        *noise = parameter;
    }
    if !ln_noise.is_null() {
        *ln_noise = (*noise).max(1.0e-38).ln();
    }
}

/// Called by b4v5noi.c for each physical noise source (host.c hook).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn CircuitOptBsim4NoiseSource(
    index: c_int,
    node1: c_int,
    node2: c_int,
    density: f64,
) {
    let device = ACTIVE_NOISE_DEVICE.load(Ordering::Acquire);
    if device.is_null() || (*device).noise_source_count >= CO_MAX_NOISE_SOURCES as c_int {
        return;
    }
    let slot = (*device).noise_source_count as usize;
    (*device).noise_source_count += 1;
    let source = &mut (*device).noise_sources[slot];
    source.index = index;
    source.node1 = node1;
    source.node2 = node2;
    source.density = density;
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn Nintegrate(
    density: f64,
    _ln_density: f64,
    _ln_last: f64,
    _data: *mut c_void,
) -> f64 {
    density
}

/// The upstream checker persists model-derived values to `bsim4v5.out`; native
/// CircuitOpt validates without writing licensed data, so this is a no-op stub
/// (host.c parity).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn BSIM4v5checkModel(
    _model: *mut ffi::BSIM4v5model,
    _instance: *mut ffi::BSIM4v5instance,
    _ckt: *mut ffi::CKTcircuit,
) -> c_int {
    0
}

// ---------------------------------------------------------------------------
// Parameter binding (host.c `co_find_param` / `co_set_param`).
// ---------------------------------------------------------------------------

unsafe fn find_param(
    base: *const ffi::IFparm,
    count: c_int,
    name: &[u8],
) -> Option<*const ffi::IFparm> {
    for i in 0..count as isize {
        let entry = base.offset(i);
        if CStr::from_ptr((*entry).keyword)
            .to_bytes()
            .eq_ignore_ascii_case(name)
        {
            return Some(entry);
        }
    }
    None
}

unsafe fn set_param(
    entry: *const ffi::IFparm,
    value: f64,
    model: bool,
    device: *mut CoBsim4,
) -> c_int {
    let mut data: ffi::IFvalue = std::mem::zeroed();
    match (*entry).dataType & IF_VARTYPES {
        v if v == IF_INTEGER || v == IF_FLAG => data.iValue = value.round() as i64 as c_int,
        v if v == IF_REAL => data.rValue = value,
        _ => return E_BADPARM,
    }
    if model {
        ffi::BSIM4v5mParam((*entry).id, &mut data, addr_of_mut!((*device).model).cast())
    } else {
        ffi::BSIM4v5param(
            (*entry).id,
            &mut data,
            addr_of_mut!((*device).instance).cast(),
            null_mut(),
        )
    }
}

#[inline]
unsafe fn model_table() -> (*const ffi::IFparm, c_int) {
    (
        addr_of!(ffi::BSIM4v5mPTable) as *const ffi::IFparm,
        addr_of!(ffi::BSIM4v5mPTSize).read(),
    )
}

#[inline]
unsafe fn instance_table() -> (*const ffi::IFparm, c_int) {
    (
        addr_of!(ffi::BSIM4v5pTable) as *const ffi::IFparm,
        addr_of!(ffi::BSIM4v5pTSize).read(),
    )
}

// ---------------------------------------------------------------------------
// Device lifecycle (host.c `co_bsim4_create` / `_destroy` / `_set_*` / `_setup`).
// ---------------------------------------------------------------------------

/// Allocate and initialise a device. Returns a null pointer on failure. The
/// caller owns the handle and must release it with [`destroy`].
pub unsafe fn create(polarity: c_int, temperature_k: f64) -> *mut CoBsim4 {
    let _guard = lock();
    ensure_frontend();

    let layout = std::alloc::Layout::new::<CoBsim4>();
    let device = std::alloc::alloc_zeroed(layout) as *mut CoBsim4;
    if device.is_null() {
        return null_mut();
    }

    (*device).model.BSIM4v5modName = MODEL_NAME.as_ptr() as *mut c_char;
    (*device).model.BSIM4v5instances = addr_of_mut!((*device).instance);
    (*device).instance.BSIM4v5modPtr = addr_of_mut!((*device).model);
    (*device).instance.BSIM4v5name = INSTANCE_NAME.as_ptr() as *mut c_char;
    (*device).instance.BSIM4v5dNode = 1;
    (*device).instance.BSIM4v5gNodeExt = 2;
    (*device).instance.BSIM4v5sNode = 3;
    (*device).instance.BSIM4v5bNode = 4;

    (*device).ckt.CKTmatrix = addr_of_mut!((*device).matrix).cast();
    (*device).ckt.CKTrhs = addr_of_mut!((*device).rhs) as *mut f64;
    (*device).ckt.CKTrhsOld = addr_of_mut!((*device).rhs_old) as *mut f64;
    (*device).ckt.CKTirhs = addr_of_mut!((*device).irhs) as *mut f64;
    (*device).ckt.CKTstates[0] = addr_of_mut!((*device).state0) as *mut f64;
    (*device).ckt.CKTstates[1] = addr_of_mut!((*device).state1) as *mut f64;
    (*device).ckt.CKTtemp = temperature_k;
    (*device).ckt.CKTnomTemp = 300.15;
    (*device).ckt.CKTmaxEqNum = 4;
    (*device).ckt.CKTabstol = 1.0e-12;
    (*device).ckt.CKTreltol = 1.0e-6;
    (*device).ckt.CKTvoltTol = 1.0e-6;
    (*device).ckt.CKTgmin = 1.0e-12;
    (*device).ckt.CKTbypass = 0;

    let name: &[u8] = if polarity > 0 { b"nmos" } else { b"pmos" };
    let (base, count) = model_table();
    match find_param(base, count, name) {
        Some(entry) if set_param(entry, 1.0, true, device) == OK => device,
        _ => {
            std::alloc::dealloc(device as *mut u8, layout);
            null_mut()
        }
    }
}

pub unsafe fn destroy(device: *mut CoBsim4) {
    if device.is_null() {
        return;
    }
    let _guard = lock();
    for i in 0..CO_MAX_NODES {
        let node = (*device).nodes[i];
        if !node.is_null() {
            libc::free(node.cast());
        }
    }
    // Leak fix (host.c never freed this): BSIM4v5temp allocates a
    // size-dependent parameter "knot" chain on the model (b4v5temp.c:364);
    // walk `pNext` and release every node.
    let mut knot = (*device).model.pSizeDependParamKnot;
    while !knot.is_null() {
        let next = (*knot).pNext;
        libc::free(knot.cast());
        knot = next;
    }
    std::alloc::dealloc(device as *mut u8, std::alloc::Layout::new::<CoBsim4>());
}

pub unsafe fn set_model(device: *mut CoBsim4, name: *const c_char, value: f64) -> c_int {
    if device.is_null() {
        return E_NOCHANGE;
    }
    let _guard = lock();
    if (*device).setup_done != 0 {
        return E_NOCHANGE;
    }
    let (base, count) = model_table();
    match find_param(base, count, CStr::from_ptr(name).to_bytes()) {
        Some(entry) => set_param(entry, value, true, device),
        None => E_BADPARM,
    }
}

pub unsafe fn set_instance(device: *mut CoBsim4, name: *const c_char, value: f64) -> c_int {
    if device.is_null() {
        return E_NOCHANGE;
    }
    let _guard = lock();
    if (*device).setup_done != 0 {
        return E_NOCHANGE;
    }
    let (base, count) = instance_table();
    match find_param(base, count, CStr::from_ptr(name).to_bytes()) {
        Some(entry) => set_param(entry, value, false, device),
        None => E_BADPARM,
    }
}

pub unsafe fn setup(device: *mut CoBsim4) -> c_int {
    if device.is_null() {
        return E_BADPARM;
    }
    let _guard = lock();
    let mut states: c_int = 0;
    let status = ffi::BSIM4v5setup(
        addr_of_mut!((*device).matrix).cast(),
        addr_of_mut!((*device).model).cast(),
        addr_of_mut!((*device).ckt),
        &mut states,
    );
    if status != OK {
        return status;
    }
    (*device).ckt.CKTnumStates = states;
    let status = ffi::BSIM4v5temp(
        addr_of_mut!((*device).model).cast(),
        addr_of_mut!((*device).ckt),
    );
    if status == OK {
        (*device).setup_done = 1;
    }
    status
}

pub unsafe fn node_count(device: *const CoBsim4) -> c_int {
    if device.is_null() {
        0
    } else {
        (*device).ckt.CKTmaxEqNum + 1
    }
}

// ---------------------------------------------------------------------------
// Dense linear solves (host.c `co_solve_real` / `co_solve_complex`), ported with
// identical partial-pivoting and elimination order for bit-level parity.
// ---------------------------------------------------------------------------

unsafe fn co_clear(device: *mut CoBsim4) {
    std::ptr::write_bytes(
        addr_of_mut!((*device).matrix) as *mut u8,
        0,
        std::mem::size_of::<MatrixFrame>(),
    );
    (*device).rhs = [0.0; CO_MAX_NODES];
    (*device).irhs = [0.0; CO_MAX_NODES];
}

fn solve_real(
    size: usize,
    matrix: &[[f64; CO_MAX_INTERNAL]; CO_MAX_INTERNAL],
    rhs: &[f64; CO_MAX_INTERNAL],
    solution: &mut [f64; CO_MAX_INTERNAL],
) -> c_int {
    let mut work = *matrix;
    let mut values = *rhs;

    for pivot in 0..size {
        let mut best = pivot;
        let mut magnitude = work[pivot][pivot].abs();
        for row in (pivot + 1)..size {
            let candidate = work[row][pivot].abs();
            if candidate > magnitude {
                magnitude = candidate;
                best = row;
            }
        }
        if magnitude < 1.0e-30 {
            return E_PANIC;
        }
        if best != pivot {
            for col in pivot..size {
                let temporary = work[pivot][col];
                work[pivot][col] = work[best][col];
                work[best][col] = temporary;
            }
            values.swap(pivot, best);
        }
        for row in (pivot + 1)..size {
            let factor = work[row][pivot] / work[pivot][pivot];
            work[row][pivot] = 0.0;
            for col in (pivot + 1)..size {
                // host.c `work[row][col] -= factor * work[pivot][col]`; clang
                // (-ffp-contract=on) fuses this to an FMA — match it exactly.
                work[row][col] = (-factor).mul_add(work[pivot][col], work[row][col]);
            }
            values[row] = (-factor).mul_add(values[pivot], values[row]);
        }
    }
    for row in (0..size).rev() {
        let mut value = values[row];
        for col in (row + 1)..size {
            value = (-work[row][col]).mul_add(solution[col], value);
        }
        solution[row] = value / work[row][row];
    }
    OK
}

#[derive(Clone, Copy)]
struct CoComplex {
    real: f64,
    imag: f64,
}

impl CoComplex {
    const ZERO: CoComplex = CoComplex {
        real: 0.0,
        imag: 0.0,
    };

    #[inline]
    fn sub(self, other: CoComplex) -> CoComplex {
        CoComplex {
            real: self.real - other.real,
            imag: self.imag - other.imag,
        }
    }
    #[inline]
    fn add(self, other: CoComplex) -> CoComplex {
        CoComplex {
            real: self.real + other.real,
            imag: self.imag + other.imag,
        }
    }
    #[inline]
    fn mul(self, other: CoComplex) -> CoComplex {
        CoComplex {
            real: self.real * other.real - self.imag * other.imag,
            imag: self.real * other.imag + self.imag * other.real,
        }
    }
    #[inline]
    fn conjugate(self) -> CoComplex {
        CoComplex {
            real: self.real,
            imag: -self.imag,
        }
    }
    #[inline]
    fn div(self, other: CoComplex) -> CoComplex {
        let scale = other.real * other.real + other.imag * other.imag;
        CoComplex {
            real: (self.real * other.real + self.imag * other.imag) / scale,
            imag: (self.imag * other.real - self.real * other.imag) / scale,
        }
    }
    #[inline]
    fn abs2(self) -> f64 {
        self.real * self.real + self.imag * self.imag
    }
}

fn solve_complex(
    size: usize,
    matrix: &[[CoComplex; CO_MAX_INTERNAL]; CO_MAX_INTERNAL],
    rhs: &[CoComplex; CO_MAX_INTERNAL],
    solution: &mut [CoComplex; CO_MAX_INTERNAL],
) -> c_int {
    let mut work = *matrix;
    let mut values = *rhs;

    for pivot in 0..size {
        let mut best = pivot;
        let mut magnitude = work[pivot][pivot].abs2();
        for row in (pivot + 1)..size {
            let candidate = work[row][pivot].abs2();
            if candidate > magnitude {
                magnitude = candidate;
                best = row;
            }
        }
        if magnitude < 1.0e-60 {
            return E_PANIC;
        }
        if best != pivot {
            for col in pivot..size {
                let temporary = work[pivot][col];
                work[pivot][col] = work[best][col];
                work[best][col] = temporary;
            }
            values.swap(pivot, best);
        }
        for row in (pivot + 1)..size {
            let factor = work[row][pivot].div(work[pivot][pivot]);
            work[row][pivot] = CoComplex::ZERO;
            for col in (pivot + 1)..size {
                work[row][col] = work[row][col].sub(factor.mul(work[pivot][col]));
            }
            values[row] = values[row].sub(factor.mul(values[pivot]));
        }
    }
    for row in (0..size).rev() {
        let mut value = values[row];
        for col in (row + 1)..size {
            value = value.sub(work[row][col].mul(solution[col]));
        }
        solution[row] = value.div(work[row][row]);
    }
    OK
}

#[inline]
unsafe fn matrix_value(device: *const CoBsim4, row: c_int, col: c_int) -> CoComplex {
    CoComplex {
        real: (*device).matrix.value[row as usize][col as usize][0],
        imag: (*device).matrix.value[row as usize][col as usize][1],
    }
}

unsafe fn device_nodes(
    device: *const CoBsim4,
    external: &mut [c_int; CO_TERMINALS],
    internal: &mut [c_int; CO_MAX_INTERNAL],
) -> c_int {
    external[0] = (*device).instance.BSIM4v5dNode;
    external[1] = (*device).instance.BSIM4v5gNodeExt;
    external[2] = (*device).instance.BSIM4v5sNode;
    external[3] = (*device).instance.BSIM4v5bNode;
    let candidates = [
        (*device).instance.BSIM4v5dNodePrime,
        (*device).instance.BSIM4v5gNodePrime,
        (*device).instance.BSIM4v5gNodeMid,
        (*device).instance.BSIM4v5sNodePrime,
        (*device).instance.BSIM4v5bNodePrime,
        (*device).instance.BSIM4v5dbNode,
        (*device).instance.BSIM4v5sbNode,
    ];
    let mut count: usize = 0;
    for &node in candidates.iter() {
        let is_external = external.contains(&node);
        let duplicate = internal[..count].contains(&node);
        if node > 0 && !is_external && !duplicate {
            if count >= CO_MAX_INTERNAL {
                return -1;
            }
            internal[count] = node;
            count += 1;
        }
    }
    count as c_int
}

// ---------------------------------------------------------------------------
// DC + small-signal core (host.c `co_bsim4_dc`). Requires the lock to be held.
// ---------------------------------------------------------------------------

#[allow(clippy::too_many_arguments)]
unsafe fn dc_inner(
    device: *mut CoBsim4,
    terminals: *const f64,
    currents: *mut f64,
    conductance: *mut f64,
    charges: *mut f64,
    capacitance: *mut f64,
    op: *mut f64,
) -> c_int {
    if device.is_null() || (*device).setup_done == 0 {
        return E_BADPARM;
    }
    let term = [
        *terminals.add(0),
        *terminals.add(1),
        *terminals.add(2),
        *terminals.add(3),
    ];

    let mut external = [0 as c_int; CO_TERMINALS];
    let mut internal = [0 as c_int; CO_MAX_INTERNAL];
    let internal_count = device_nodes(device, &mut external, &mut internal);
    if internal_count < 0 {
        return E_UNSUPP;
    }
    let internal_count = internal_count as usize;

    for i in 0..CO_TERMINALS {
        (*device).rhs_old[external[i] as usize] = term[i];
    }
    if internal_count >= 1 && (*device).rhs_old[internal[0] as usize] == 0.0 {
        (*device).rhs_old[internal[0] as usize] = term[0];
    }
    if internal_count >= 2 && (*device).rhs_old[internal[1] as usize] == 0.0 {
        (*device).rhs_old[internal[1] as usize] = term[2];
    }

    (*device).ckt.CKTmode = MODEDCOP | MODEINITFLOAT;
    for iteration in 0..40 {
        co_clear(device);
        let status = ffi::BSIM4v5load(
            addr_of_mut!((*device).model).cast(),
            addr_of_mut!((*device).ckt),
        );
        if status != OK {
            return status;
        }
        if internal_count == 0 {
            break;
        }

        let mut system = [[0.0f64; CO_MAX_INTERNAL]; CO_MAX_INTERNAL];
        let mut right = [0.0f64; CO_MAX_INTERNAL];
        let mut next = [0.0f64; CO_MAX_INTERNAL];
        for row in 0..internal_count {
            right[row] = (*device).rhs[internal[row] as usize];
            for j in 0..CO_TERMINALS {
                let m = (*device).matrix.value[internal[row] as usize][external[j] as usize][0];
                right[row] = (-m).mul_add(term[j], right[row]);
            }
            for col in 0..internal_count {
                system[row][col] =
                    (*device).matrix.value[internal[row] as usize][internal[col] as usize][0];
            }
        }
        let status = solve_real(internal_count, &system, &right, &mut next);
        if status != OK {
            return status;
        }
        let mut error = 0.0f64;
        for i in 0..internal_count {
            error = error.max((next[i] - (*device).rhs_old[internal[i] as usize]).abs());
            (*device).rhs_old[internal[i] as usize] = next[i];
        }
        if error < 1.0e-12 {
            break;
        }
        if iteration == 39 {
            return E_PANIC;
        }
    }

    co_clear(device);
    let status = ffi::BSIM4v5load(
        addr_of_mut!((*device).model).cast(),
        addr_of_mut!((*device).ckt),
    );
    if status != OK {
        return status;
    }

    for row in 0..CO_TERMINALS {
        let r = external[row] as usize;
        let mut residual = -(*device).rhs[r];
        for col in 0..CO_TERMINALS {
            let m = (*device).matrix.value[r][external[col] as usize][0];
            residual = m.mul_add(term[col], residual);
        }
        for col in 0..internal_count {
            let m = (*device).matrix.value[r][internal[col] as usize][0];
            residual = m.mul_add((*device).rhs_old[internal[col] as usize], residual);
        }
        *currents.add(row) = residual;
    }

    for row in 0..CO_TERMINALS {
        for col in 0..CO_TERMINALS {
            let mut reduced =
                (*device).matrix.value[external[row] as usize][external[col] as usize][0];
            if internal_count > 0 {
                let mut system = [[0.0f64; CO_MAX_INTERNAL]; CO_MAX_INTERNAL];
                let mut right = [0.0f64; CO_MAX_INTERNAL];
                let mut solution = [0.0f64; CO_MAX_INTERNAL];
                for i in 0..internal_count {
                    right[i] =
                        (*device).matrix.value[internal[i] as usize][external[col] as usize][0];
                    for j in 0..internal_count {
                        system[i][j] =
                            (*device).matrix.value[internal[i] as usize][internal[j] as usize][0];
                    }
                }
                let status = solve_real(internal_count, &system, &right, &mut solution);
                if status != OK {
                    return status;
                }
                for i in 0..internal_count {
                    let m = (*device).matrix.value[external[row] as usize][internal[i] as usize][0];
                    reduced = (-m).mul_add(solution[i], reduced);
                }
            }
            *conductance.add(row * CO_TERMINALS + col) = reduced;
        }
    }

    (*device).ckt.CKTmode = MODEDCOP | MODEINITSMSIG;
    co_clear(device);
    let status = ffi::BSIM4v5load(
        addr_of_mut!((*device).model).cast(),
        addr_of_mut!((*device).ckt),
    );
    if status != OK {
        return status;
    }
    let state_base = (*device).instance.BSIM4v5states;
    *charges.add(0) = (*device).state0[(state_base + OFF_QD) as usize];
    *charges.add(1) = (*device).state0[(state_base + OFF_QG) as usize];
    *charges.add(2) = (*device).state0[(state_base + OFF_QS) as usize];
    *charges.add(3) = (*device).state0[(state_base + OFF_QB) as usize];
    if (*device).instance.BSIM4v5rbodyMod != 0 {
        *charges.add(3) += (*device).state0[(state_base + OFF_QBD) as usize];
        *charges.add(3) += (*device).state0[(state_base + OFF_QBS) as usize];
    }
    let model_type = (*device).model.BSIM4v5type as f64;
    for terminal in 0..CO_TERMINALS {
        *charges.add(terminal) *= model_type;
    }

    (*device).ckt.CKTomega = 1.0;
    co_clear(device);
    let status = ffi::BSIM4v5acLoad(
        addr_of_mut!((*device).model).cast(),
        addr_of_mut!((*device).ckt),
    );
    if status != OK {
        return status;
    }
    for row in 0..CO_TERMINALS {
        for col in 0..CO_TERMINALS {
            let mut reduced = matrix_value(device, external[row], external[col]);
            if internal_count > 0 {
                let mut system = [[CoComplex::ZERO; CO_MAX_INTERNAL]; CO_MAX_INTERNAL];
                let mut right = [CoComplex::ZERO; CO_MAX_INTERNAL];
                let mut solution = [CoComplex::ZERO; CO_MAX_INTERNAL];
                for i in 0..internal_count {
                    right[i] = matrix_value(device, internal[i], external[col]);
                    for j in 0..internal_count {
                        system[i][j] = matrix_value(device, internal[i], internal[j]);
                    }
                }
                let status = solve_complex(internal_count, &system, &right, &mut solution);
                if status != OK {
                    return status;
                }
                for i in 0..internal_count {
                    reduced = reduced
                        .sub(matrix_value(device, external[row], internal[i]).mul(solution[i]));
                }
            }
            *capacitance.add(row * CO_TERMINALS + col) = reduced.imag;
        }
    }

    *op.add(0) = (*device).instance.BSIM4v5cd;
    *op.add(1) = (*device).instance.BSIM4v5gm;
    *op.add(2) = (*device).instance.BSIM4v5gds;
    *op.add(3) = (*device).instance.BSIM4v5gmbs;
    *op.add(4) = (*device).instance.BSIM4v5von;
    *op.add(5) = (*device).instance.BSIM4v5vdsat;
    *op.add(6) = (*device).instance.BSIM4v5ueff;
    *op.add(7) = internal_count as f64;
    OK
}

/// In-C conservation snap (host.c `co_bsim4_enforce_terminal_conservation`).
unsafe fn enforce_terminal_conservation(
    currents: *mut f64,
    conductance: *mut f64,
    charges: *mut f64,
    capacitance: *mut f64,
) -> c_int {
    let mut current_error: f64 = 0.0;
    let mut current_scale: f64 = 1.0e-18;
    let mut charge_error: f64 = 0.0;
    let mut charge_scale: f64 = 1.0e-24;
    for terminal in 0..CO_TERMINALS {
        current_error += *currents.add(terminal);
        current_scale = current_scale.max((*currents.add(terminal)).abs());
        charge_error += *charges.add(terminal);
        charge_scale = charge_scale.max((*charges.add(terminal)).abs());
    }
    if current_error.abs() > (1.0e-8 * current_scale).max(1.0e-9) {
        return E_PANIC;
    }
    if charge_error.abs() > (1.0e-8 * charge_scale).max(1.0e-18) {
        return E_PANIC;
    }
    *currents.add(CO_TERMINALS - 1) -= current_error;
    *charges.add(CO_TERMINALS - 1) -= charge_error;

    let mut conductance_scale: f64 = 1.0e-18;
    let mut capacitance_scale: f64 = 1.0e-24;
    for offset in 0..CO_TERMINALS * CO_TERMINALS {
        conductance_scale = conductance_scale.max((*conductance.add(offset)).abs());
        capacitance_scale = capacitance_scale.max((*capacitance.add(offset)).abs());
    }
    for column in 0..CO_TERMINALS {
        let mut conductance_error: f64 = 0.0;
        let mut capacitance_error: f64 = 0.0;
        for row in 0..CO_TERMINALS {
            conductance_error += *conductance.add(row * CO_TERMINALS + column);
            capacitance_error += *capacitance.add(row * CO_TERMINALS + column);
        }
        if conductance_error.abs() > (1.0e-8 * conductance_scale).max(1.0e-9) {
            return E_PANIC;
        }
        if capacitance_error.abs() > (1.0e-8 * capacitance_scale).max(1.0e-18) {
            return E_PANIC;
        }
        *conductance.add((CO_TERMINALS - 1) * CO_TERMINALS + column) -= conductance_error;
        *capacitance.add((CO_TERMINALS - 1) * CO_TERMINALS + column) -= capacitance_error;
    }
    OK
}

// ---------------------------------------------------------------------------
// Public locked entry points (map 1:1 to the C ABI in co-py).
// ---------------------------------------------------------------------------

#[allow(clippy::too_many_arguments)]
pub unsafe fn dc(
    device: *mut CoBsim4,
    terminals: *const f64,
    currents: *mut f64,
    conductance: *mut f64,
    charges: *mut f64,
    capacitance: *mut f64,
    op: *mut f64,
) -> c_int {
    let _guard = lock();
    dc_inner(
        device,
        terminals,
        currents,
        conductance,
        charges,
        capacitance,
        op,
    )
}

#[allow(clippy::too_many_arguments)]
pub unsafe fn eval(
    device: *mut CoBsim4,
    terminals: *const f64,
    currents: *mut f64,
    conductance: *mut f64,
    charges: *mut f64,
    capacitance: *mut f64,
    op: *mut f64,
) -> c_int {
    let _guard = lock();
    let status = dc_inner(
        device,
        terminals,
        currents,
        conductance,
        charges,
        capacitance,
        op,
    );
    if status != OK {
        return status;
    }
    enforce_terminal_conservation(currents, conductance, charges, capacitance)
}

/// All-`void*` evaluation ABI (host.c `co_bsim4_eval_vp`), for the Numba bridge.
pub unsafe fn eval_vp(
    device: *mut CoBsim4,
    terminals: *const f64,
    currents: *mut f64,
    conductance: *mut f64,
    charges: *mut f64,
    capacitance: *mut f64,
) -> c_int {
    let mut op = [0.0f64; 8];
    eval(
        device,
        terminals,
        currents,
        conductance,
        charges,
        capacitance,
        op.as_mut_ptr(),
    )
}

pub unsafe fn noise(
    device: *mut CoBsim4,
    frequency_hz: f64,
    total_real: *mut f64,
    total_imag: *mut f64,
    flicker_real: *mut f64,
    flicker_imag: *mut f64,
) -> c_int {
    // `!(f > 0.0)` (not the "cleaner" `f <= 0.0`) is deliberate host.c parity:
    // it also rejects NaN, which `<=` would accept.
    #[allow(clippy::neg_cmp_op_on_partial_ord)]
    if device.is_null() || (*device).setup_done == 0 || !(frequency_hz > 0.0) {
        return E_BADPARM;
    }
    let _guard = lock();

    let mut external = [0 as c_int; CO_TERMINALS];
    let mut internal = [0 as c_int; CO_MAX_INTERNAL];
    let internal_count = device_nodes(device, &mut external, &mut internal);
    if internal_count < 0 {
        return E_UNSUPP;
    }
    let internal_count = internal_count as usize;

    (*device).ckt.CKTomega = 2.0 * CO_PI * frequency_hz;
    co_clear(device);
    let status = ffi::BSIM4v5acLoad(
        addr_of_mut!((*device).model).cast(),
        addr_of_mut!((*device).ckt),
    );
    if status != OK {
        return status;
    }

    let mut job: ffi::NOISEAN = std::mem::zeroed();
    let mut data: ffi::Ndata = std::mem::zeroed();
    job.NstartFreq = frequency_hz;
    data.freq = frequency_hz;
    data.GainSqInv = 1.0;
    (*device).noise_source_count = 0;
    let previous_job = (*device).ckt.CKTcurJob;
    (*device).ckt.CKTcurJob = addr_of_mut!(job).cast();
    ACTIVE_NOISE_DEVICE.store(device, Ordering::Release);
    let mut total_density = 0.0f64;
    let status = ffi::BSIM4v5noise(
        N_DENS,
        N_CALC,
        addr_of_mut!((*device).model).cast(),
        addr_of_mut!((*device).ckt),
        &mut data,
        &mut total_density,
    );
    ACTIVE_NOISE_DEVICE.store(null_mut(), Ordering::Release);
    (*device).ckt.CKTcurJob = previous_job;
    if status != OK {
        return status;
    }

    let mut total = [[CoComplex::ZERO; CO_TERMINALS]; CO_TERMINALS];
    let mut flicker = [[CoComplex::ZERO; CO_TERMINALS]; CO_TERMINALS];

    for source_index in 0..(*device).noise_source_count as usize {
        let source = (*device).noise_sources[source_index];
        if !source.density.is_finite() || source.density < 0.0 {
            return E_PARMVAL;
        }
        if source.density == 0.0 {
            continue;
        }

        let mut external_incidence = [CoComplex::ZERO; CO_TERMINALS];
        let mut internal_incidence = [CoComplex::ZERO; CO_MAX_INTERNAL];
        for terminal in 0..CO_TERMINALS {
            if source.node1 == external[terminal] {
                external_incidence[terminal].real += 1.0;
            }
            if source.node2 == external[terminal] {
                external_incidence[terminal].real -= 1.0;
            }
        }
        for index in 0..internal_count {
            if source.node1 == internal[index] {
                internal_incidence[index].real += 1.0;
            }
            if source.node2 == internal[index] {
                internal_incidence[index].real -= 1.0;
            }
        }

        let mut internal_voltage = [CoComplex::ZERO; CO_MAX_INTERNAL];
        if internal_count > 0 {
            let mut system = [[CoComplex::ZERO; CO_MAX_INTERNAL]; CO_MAX_INTERNAL];
            for row in 0..internal_count {
                for col in 0..internal_count {
                    system[row][col] = matrix_value(device, internal[row], internal[col]);
                }
            }
            let status = solve_complex(
                internal_count,
                &system,
                &internal_incidence,
                &mut internal_voltage,
            );
            if status != OK {
                return status;
            }
        }

        let mut reduced = [CoComplex::ZERO; CO_TERMINALS];
        for terminal in 0..CO_TERMINALS {
            reduced[terminal] = external_incidence[terminal];
            for index in 0..internal_count {
                reduced[terminal] = reduced[terminal].sub(
                    matrix_value(device, external[terminal], internal[index])
                        .mul(internal_voltage[index]),
                );
            }
        }
        for row in 0..CO_TERMINALS {
            for col in 0..CO_TERMINALS {
                let mut contribution = reduced[row].mul(reduced[col].conjugate());
                contribution.real *= source.density;
                contribution.imag *= source.density;
                total[row][col] = total[row][col].add(contribution);
                if source.index == BSIM4V5_FLNOIZ {
                    flicker[row][col] = flicker[row][col].add(contribution);
                }
            }
        }
    }

    for row in 0..CO_TERMINALS {
        for col in 0..CO_TERMINALS {
            let offset = row * CO_TERMINALS + col;
            *total_real.add(offset) = total[row][col].real;
            *total_imag.add(offset) = total[row][col].imag;
            *flicker_real.add(offset) = flicker[row][col].real;
            *flicker_imag.add(offset) = flicker[row][col].imag;
        }
    }
    OK
}

/// Batch evaluation over independent handles (host.c `co_bsim4_eval_batch`).
#[allow(clippy::too_many_arguments)]
pub unsafe fn eval_batch(
    devices: *const *mut CoBsim4,
    count: usize,
    terminals: *const f64,
    currents: *mut f64,
    conductance: *mut f64,
    charges: *mut f64,
    capacitance: *mut f64,
    statuses: *mut c_int,
) -> c_int {
    let mut first_error = OK;
    for index in 0..count {
        let status = eval_vp(
            *devices.add(index),
            terminals.add(index * CO_TERMINALS),
            currents.add(index * CO_TERMINALS),
            conductance.add(index * CO_TERMINALS * CO_TERMINALS),
            charges.add(index * CO_TERMINALS),
            capacitance.add(index * CO_TERMINALS * CO_TERMINALS),
        );
        if !statuses.is_null() {
            *statuses.add(index) = status;
        }
        if first_error == OK && status != OK {
            first_error = status;
        }
    }
    first_error
}

// ---------------------------------------------------------------------------
// Build metadata (surfaced to Python through co-py `engine_info()`).
// ---------------------------------------------------------------------------

/// Canonical crate version.
pub fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

/// Stable four-terminal ABI version.
pub fn abi_version() -> u32 {
    ABI_VERSION
}

/// Minimal numeric ABI probe retained for build and linkage diagnostics.
pub fn model_probe(x: f64) -> f64 {
    x + 1.0
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal but valid NMOS card: create sets the polarity, then a couple of
    /// geometry/oxide parameters keep BSIM4's defaults in a working regime.
    unsafe fn make_device(polarity: c_int) -> *mut CoBsim4 {
        let device = create(polarity, 300.15);
        assert!(!device.is_null(), "create returned null");
        assert_eq!(set_model(device, c"tnom".as_ptr(), 27.0), OK);
        assert_eq!(set_model(device, c"toxe".as_ptr(), 1.4e-9), OK);
        assert_eq!(set_model(device, c"toxp".as_ptr(), 1.4e-9), OK);
        assert_eq!(set_instance(device, c"w".as_ptr(), 1.0e-6), OK);
        assert_eq!(set_instance(device, c"l".as_ptr(), 1.0e-7), OK);
        assert_eq!(set_instance(device, c"nf".as_ptr(), 1.0), OK);
        assert_eq!(setup(device), OK, "setup failed");
        device
    }

    #[test]
    fn version_is_nonempty() {
        assert!(!version().is_empty());
        assert_eq!(abi_version(), 1);
    }

    #[test]
    fn unknown_parameter_is_reported() {
        unsafe {
            let device = create(1, 300.15);
            assert!(!device.is_null());
            assert_eq!(
                set_model(device, c"definitely_not_a_param".as_ptr(), 1.0),
                E_BADPARM
            );
            destroy(device);
        }
    }

    #[test]
    fn eval_point_is_finite_and_conserved() {
        unsafe {
            let device = make_device(1);
            let terminals = [0.6f64, 0.6, 0.0, 0.0]; // (drain, gate, source, bulk)
            let mut currents = [0.0f64; 4];
            let mut conductance = [0.0f64; 16];
            let mut charges = [0.0f64; 4];
            let mut capacitance = [0.0f64; 16];
            let mut op = [0.0f64; 8];
            let status = eval(
                device,
                terminals.as_ptr(),
                currents.as_mut_ptr(),
                conductance.as_mut_ptr(),
                charges.as_mut_ptr(),
                capacitance.as_mut_ptr(),
                op.as_mut_ptr(),
            );
            assert_eq!(status, OK, "eval failed");
            assert!(currents.iter().all(|v| v.is_finite()));
            assert!(conductance.iter().all(|v| v.is_finite()));
            assert!(charges.iter().all(|v| v.is_finite()));
            assert!(capacitance.iter().all(|v| v.is_finite()));

            // KCL: terminal currents sum to ~0.
            let current_sum: f64 = currents.iter().sum();
            let current_scale = currents.iter().fold(1e-18_f64, |m, v| m.max(v.abs()));
            assert!(
                current_sum.abs() <= 1e-9_f64.max(1e-8 * current_scale),
                "KCL: {current_sum:e}"
            );

            // Charge conservation: terminal charges sum to ~0.
            let charge_sum: f64 = charges.iter().sum();
            assert!(charge_sum.abs() <= 1e-25, "charge sum {charge_sum:e}");

            // Conductance columns sum to ~0 after the conservation snap.
            for col in 0..4 {
                let col_sum: f64 = (0..4).map(|row| conductance[row * 4 + col]).sum();
                assert!(col_sum.abs() <= 1e-9, "G column {col} sum {col_sum:e}");
            }
            destroy(device);
        }
    }

    #[test]
    fn noise_is_finite_hermitian() {
        unsafe {
            let device = make_device(1);
            let terminals = [0.6f64, 0.6, 0.0, 0.0];
            let mut c = [0.0f64; 4];
            let mut g = [0.0f64; 16];
            let mut q = [0.0f64; 4];
            let mut cap = [0.0f64; 16];
            let mut op = [0.0f64; 8];
            assert_eq!(
                eval(
                    device,
                    terminals.as_ptr(),
                    c.as_mut_ptr(),
                    g.as_mut_ptr(),
                    q.as_mut_ptr(),
                    cap.as_mut_ptr(),
                    op.as_mut_ptr()
                ),
                OK
            );
            let mut tr = [0.0f64; 16];
            let mut ti = [0.0f64; 16];
            let mut fr = [0.0f64; 16];
            let mut fi = [0.0f64; 16];
            let status = noise(
                device,
                1.0e6,
                tr.as_mut_ptr(),
                ti.as_mut_ptr(),
                fr.as_mut_ptr(),
                fi.as_mut_ptr(),
            );
            assert_eq!(status, OK, "noise failed");
            assert!(tr.iter().all(|v| v.is_finite()) && ti.iter().all(|v| v.is_finite()));
            // Diagonal PSD is real and non-negative.
            for k in 0..4 {
                assert!(tr[k * 4 + k] >= -1e-30, "PSD[{k}] = {}", tr[k * 4 + k]);
            }
            destroy(device);
        }
    }

    /// Repeated create/setup/eval/destroy must not panic or leak. The knot-chain
    /// free in `destroy` keeps RSS flat (the external RSS gate confirms it); here
    /// we simply exercise the full lifecycle many times.
    #[test]
    fn repeated_lifecycle_is_stable() {
        unsafe {
            for _ in 0..400 {
                let device = make_device(1);
                let terminals = [0.5f64, 0.5, 0.0, 0.0];
                let mut c = [0.0f64; 4];
                let mut g = [0.0f64; 16];
                let mut q = [0.0f64; 4];
                let mut cap = [0.0f64; 16];
                let mut op = [0.0f64; 8];
                assert_eq!(
                    eval(
                        device,
                        terminals.as_ptr(),
                        c.as_mut_ptr(),
                        g.as_mut_ptr(),
                        q.as_mut_ptr(),
                        cap.as_mut_ptr(),
                        op.as_mut_ptr()
                    ),
                    OK
                );
                destroy(device);
            }
        }
    }
}
